services:
  - type: web
    name: butterbakery-postgres
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
    plan: free
